Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provision "shell", inline: "apt-get update && apt-get install -y python3"

  # RKE2 Server (Master)
  config.vm.define "rke2-server" do |server|
    server.vm.hostname = "rke2-server"
    server.vm.network "private_network", ip: "192.168.56.120"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
  end

  # RKE2 Agent 1
  config.vm.define "rke2-agent-1" do |agent|
    agent.vm.hostname = "rke2-agent-1"
    agent.vm.network "private_network", ip: "192.168.56.121"
    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end

  # RKE2 Agent 2
  config.vm.define "rke2-agent-2" do |agent|
    agent.vm.hostname = "rke2-agent-2"
    agent.vm.network "private_network", ip: "192.168.56.122"
    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end
end
