Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "openldap-server"
  config.vm.network "private_network", ip: "192.168.56.115"
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"
  config.ssh.verify_host_key = false

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = 1
  end

end
